### ISSUE TITLE
Browser mobile adaptation adjustment

### ISSUE THREAD

**Issue by lance052801** [TurnNetwork/turn-browser#11]
![img_v3_0270_eb8c079b-0220-4789-b84f-7ac7ac26602g](https://github.com/TurnNetwork/turn-browser/assets/153878291/169591a5-4a95-4138-bcc4-9ed5d65bd94a)

**Comment by rinimmp** [comment]
done

**Comment by lance052801** [comment]
![image](https://github.com/TurnNetwork/turn-browser/assets/153878291/f5f38705-b5bf-4d9d-9a94-985dc94a9318)
The navigation bar at the top of the browser is not displayed

**Comment by rinimmp** [comment]
done
