### ISSUE TITLE
contact details details page, details style debugging adjustment

### ISSUE THREAD

**Issue by lance052801** [TurnNetwork/turn-browser#12]
![image](https://github.com/TurnNetwork/turn-browser/assets/153878291/c41e6431-fd1e-4fc4-a762-1b49193de21d)
expect：
![image](https://github.com/TurnNetwork/turn-browser/assets/153878291/3897effe-e921-4bf7-abdb-b90438d12d59)

**Comment by rinimmp** [comment]
done
